name: ticktobrain
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0-323.2.beta

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  in_app_review: ^2.0.9
  intl: ^0.18.0
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  webview_flutter: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.12
  change_app_package_name: ^1.4.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  icons_launcher: ^3.0.0-beta.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/playstore.png
